### ISSUE TITLE
翻译器无法加载

### ISSUE THREAD

**Issue by Cecropis** [HunterShenSmzh/Xunity-TGW#1]
![image](https://github.com/HunterShenSmzh/Xunity-TGW/assets/30413607/6d3d5a4e-b067-4561-b2f5-7c8878ac7815)
好像是是.net的版本问题？这个需要哪个版本？

**Comment by HunterShenSmzh** [comment]
Xunity是最新的版本么？这个情况是定义和引用不一致导致的。也许可以考虑更新一下？

**Comment by HunterShenSmzh** [comment]
看了眼需要net3，安装一下说不定可以解决。

**Comment by Cecropis** [comment]
我测了一下，同一个游戏用bepinex可以加载但是ReiPatcher的不行。bepinex版本5.4.22.0，xunity版本5.3.0

**Comment by Cecropis** [comment]
哦哦，好像还是用不了的状态
[LogOutput.log](https://github.com/HunterShenSmzh/Xunity-TGW/files/15051164/LogOutput.log)

**Comment by HunterShenSmzh** [comment]
> 哦哦，好像还是用不了的状态 [LogOutput.log](https://github.com/HunterShenSmzh/Xunity-TGW/files/15051164/LogOutput.log)

我更新了一个新的方法，用自带的默认CustomURL，转接去tgw，应该可以解决了
